tasks:
  - name: Run game
    init: g++ -o memory_game src/memory_game
    command: ./memory_game

github:
  prebuilds:
    addBadge: true
    addComment: false
    addCheck: false
    master: true
    branches: true
    pullRequestsFromForks: true

vscode:
  extensions:
  # - ms-vscode.cpptools
    - twxs.cmake
    - ms-vscode.cmake-tools
    - notskm.clang-tidy
